resolver: nightly-2016-03-28
packages:
- '.'
- location:
    git: git@github.com:cocreature/nanovg-hs.git
    commit: 5558aef3381b2e95b38c8e3d0d66f0842f4ed668
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
